### PR TITLE
Vite6

### PR DESCRIPTION
**Pull request by mrginglymus**
This is an extension of https://github.com/privatenumber/vite-css-modules/pull/14, because I'd like to use this myself again.

I had to rollback typescript as pnpm doesn't seem to like typescript 5.6 (more of a yarn person myself)...`tsc` was throwing all lkinds of weird errors that a rollback to 5.5.4 (or a switch to yarn) fixed. I then noticed that `tsc` wasn't run as part of the CI job, so added that.

The missing filename I think is trivial; the test harness doesn't provide a closest package.json, so let's just provide the static name as suggested. I then took the commit from #14, massaged the types, and the tests seem to pass!

closes https://github.com/privatenumber/vite-css-modules/pull/14
fixes https://github.com/privatenumber/vite-css-modules/issues/13

### CODE REVIEW

**Comment by privatenumber** [comment]
Thanks, I'll try to review over the weekend!

**Comment by mrginglymus** [comment]
I've been unable to reproduce this since in storybook

**Comment by privatenumber** [comment]
Thank you @mrginglymus & @skewballfox !

**Pull request merged**
